export const ADD_VOITURE="ADD_VOITURE";
export const DELETE_VOITURE="DELETE_VOITURE";
export const UPDATE_VOITURE="UPDATE_VOITURE";
export const FILTRER_VOITURE="FILTRER_VOITURE";
export const DELETE_ALL_VOITURES="DELETE_ALL_VOITURES";