export const ADD_RESERVATION="ADD_RESERVATION";
export const DELETE_RESERVATION="DELETE_RESERVATION";
export const UPDATE_RESERVATION="UPDATE_RESERVATION";
export const DELETE_ALL_RESERVATION="DELETE_ALL_RESERVATION";