export const INSCRIPTION_USER="INSCRIPTION_USER";
export const CONNEXION_ADMIN="CONNEXION_ADMIN";
export const CONNEXION_USER="CONNEXION_USER";
export const DECONNEXION_USER='DECONNEXION_USER';
export const DECONNEXION_ADMIN='DECONNEXION_ADMIN';